# Generated by Django 3.0.8 on 2020-09-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200917_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
